# Generated by Django 5.1.6 on 2025-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(db_column='word', unique=True)),
                ('Pronunciation', models.TextField(db_column='pronunciation')),
                ('Definition', models.TextField(db_column='definition')),
                ('Hine', models.TextField(db_column='hint')),
                ('SampleSentence', models.TextField(db_column='sample_sentence')),
            ],
            options={
                'db_table': 'flash_cards',
            },
        ),
    ]
